let routes = [
    {
        path:"/",
        component:{
            template:"<home></home>"
        }
    },
    {
        path:"/admin-dashboard",
        component:{
            template:"<admin-dashboard></admin-dashboard>"
        }
    },
    {
        path:"/charts",
        component:{
            template:"<charts></charts>"
        }
    },
    {
        path:"/support",
        component:{
            template:'<support></support>'
        }
    },
    {
        path:"/user-home",
        component:{
            template:"<user-home></user-home>"
        }
    },
    {
        path:"/new",
        component:{
            template:"<new></new>"
        }
    },
    {
        path:'/register',
        component:{
            template:'<register></register>'
        }
    },
    {
        path:'/payment-success/:transaction_id',
        component:{
            template:'<payment-success></payment-success>'
        }
    },
    {
        path:'/support-form',
        component:{
            template:'<support-form></support-form>'
        }
    }
]
let router = new VueRouter({
    routes
})